SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `tiankong_mfk`.`bill` ADD COLUMN `price` FLOAT(11) NOT NULL  AFTER `cost` , ADD COLUMN `count` INT(11) NOT NULL  AFTER `price` , CHANGE COLUMN `name` `name` VARCHAR(45) NOT NULL  , CHANGE COLUMN `cost` `cost` FLOAT(11) NOT NULL  ;

ALTER TABLE `tiankong_mfk`.`problem` ADD COLUMN `fixProplePhone` VARCHAR(11) NULL DEFAULT NULL COMMENT '维修人电话'  AFTER `fixProple` , ADD COLUMN `twentyFourHour` INT(11) NOT NULL DEFAULT false COMMENT '是否进行过24小时提醒，提醒一次后不再提醒'  AFTER `fixProplePhone` , CHANGE COLUMN `title` `title` VARCHAR(255) NOT NULL COMMENT '问题标题'  , CHANGE COLUMN `content` `content` LONGTEXT NOT NULL COMMENT '问题描述'  , CHANGE COLUMN `phone` `phone` VARCHAR(11) NOT NULL COMMENT '提问题者的电话'  , CHANGE COLUMN `starContent` `starContent` LONGTEXT NULL DEFAULT NULL COMMENT '评价内容'  , CHANGE COLUMN `chargeContent` `reason` LONGTEXT NULL DEFAULT NULL COMMENT '问题原因'  , CHANGE COLUMN `result` `result` LONGTEXT NULL DEFAULT NULL COMMENT '维修结果'  , CHANGE COLUMN `totalCharge` `totalCharge` VARCHAR(255) NULL DEFAULT NULL COMMENT '总共花费'  , CHANGE COLUMN `total_time` `total_time` VARCHAR(255) NULL DEFAULT NULL COMMENT '总用时\n从提问题到问题解决。'  , CHANGE COLUMN `realName` `realName` VARCHAR(45) NOT NULL  , CHANGE COLUMN `fixProple` `fixProple` VARCHAR(45) NULL DEFAULT NULL COMMENT '维修人'  ;

CREATE  TABLE IF NOT EXISTS `tiankong_mfk`.`smg_catch` (
  `id` INT(11) NOT NULL ,
  `phone` VARCHAR(11) NOT NULL ,
  `content` VARCHAR(512) NOT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = latin1_swedish_ci;

DROP TABLE IF EXISTS `tiankong_mfk`.`message_log` ;

DROP TABLE IF EXISTS `tiankong_mfk`.`login_log` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
