SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `tiankong_mfk`.`problem` ADD COLUMN `fixProple` VARCHAR(45) NULL DEFAULT NULL  AFTER `realName` , CHANGE COLUMN `state` `state` INT(11) NOT NULL COMMENT '1 ask -> wait to  check\n2 ac  -> wait to accept\n3 fix  -> fixxing\n4 finish ->wait to evaluate\n5  evaluate -> over\n6 not pass the check'  , CHANGE COLUMN `reason` `chargeContent` LONGTEXT NULL DEFAULT NULL COMMENT '问题原因'  , CHANGE COLUMN `total_bill` `totalCharge` VARCHAR(255) NULL DEFAULT NULL  ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
