SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `tiankong_mfk`.`bill` ADD COLUMN `pro_id` INT(11) NOT NULL  AFTER `count` , 
  ADD CONSTRAINT `fk_bill_problem1`
  FOREIGN KEY (`id` )
  REFERENCES `tiankong_mfk`.`problem` (`id` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `tiankong_mfk`.`problem` DROP COLUMN `reason` , ADD COLUMN `reason` LONGTEXT NULL DEFAULT NULL COMMENT '问题原因'  AFTER `state` , CHANGE COLUMN `twentyFourHour` `twentyFourHour` INT(11) NOT NULL DEFAULT false COMMENT '是否进行过24小时提醒，提醒一次后不再提醒'  ;

DROP TABLE IF EXISTS `tiankong_mfk`.`map_pro_bill` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
